[package]
name = "gaming-viewer"
version = "0.1.0"
description = "An app to view clips."
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { git = "https://github.com/tauri-apps/tauri", branch = "feat/cef", features = [
] }

[dependencies]
tauri-plugin-opener = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "feat/cef" }
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "feat/cef", features = [
    "common-controls-v6",
    "compression",
    "protocol-asset",
    "tray-icon"
], default-features = false }
tauri-plugin-shell = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "feat/cef" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-fs = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "feat/cef" }
filetime = "0.2"
tauri-plugin-dialog = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "feat/cef" }
chrono = "0.4"
dirs = "6.0"
regex = "1.9.0"
walkdir = "2.3"
tokio = { version = "1.37", features = ["rt", "macros"] }
gtk = "0.18"

[patch.crates-io]
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "feat/cef" }
tauri-plugin = { git = "https://github.com/tauri-apps/tauri", branch = "feat/cef" }

[features]
default = ["cef"]
cef = ["tauri/cef"]
